### ISSUE TITLE
Some change with this code

### ISSUE THREAD

**Issue by Wogwan** [jumlauft/Safe-Online-Learning-for-Gaussian-Processes#1]
Hi Jumlauft, appreciate for your gorgeous work for safe-online-learning-for GP! Here is some simple questions which trouble me for a long time: can we use it to learn the autonomous system with partial unknown dynamics, such as this form: \dot_{x} = f(x) + d(x). Noting that system did not contain the controller. Sorry, maybe it is a simple question, but that really big to me. Hoping hearing from you if available. Best regards, wogwan

**Comment by jumlauft** [comment]
Dear Wogwan, 
great to hear about your interest in our work. Partial or prior knowledge can be included using a prior mean function. To read more about this and the implementation check out [this Matlab documentation](https://de.mathworks.com/help/stats/gaussian-process-regression-models.html).
Best wishes, Jonas

**Comment by Wogwan** [comment]
Dear Jonas, 
thanks for your reply! Great appreciate for that.
Best regards, Wogwan
